---
- name: Update system with dnf
  become: yes
  dnf:
    name: "*"
    state: "latest"
    exclude: "{{ exclude_pkgs | default(omit) }}"

- name: Autoremove unused packages
  become: yes
  dnf:
    autoremove: yes

- name: Reboot required
  become: yes
  command: "dnf needs-restarting -r"
  register: reboot_required
  ignore_errors: True
  changed_when: False
  failed_when: reboot_required.rc == 2
