---
- include_tasks: yum_update.yml
  when: ansible_facts['pkg_mgr'] == 'yum'

- include_tasks: dnf_update.yml
  when: ansible_facts['pkg_mgr'] == 'dnf'

- name: Reboot
  reboot:
    post_reboot_delay: 60
  throttle: 1
  when: reboot_required.rc == 1