---
- name: Update system with yum
  become: yes
  yum:
    name: "*"
    state: "latest"
  when: ansible_facts['pkg_mgr'] == 'yum'
  
- name: Update system with dnf
  become: yes
  dnf:
    name: "*"
    state: "latest"
  when: ansible_facts['pkg_mgr'] == 'dnf'